// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <printer.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string __Pri__Printer_ids[2] =
{
    "::Ice::Object",
    "::Pri::Printer"
};
const ::std::string __Pri__Printer_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "pStr"
};
const ::std::string __Pri__Printer__pStr_name = "pStr";

}

void
Pri::PrinterPrx::__pStr(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<Result_pStr>>& __outAsync, const ::Ice::Context& __ctx)
{
    __checkAsyncTwowayOnly(__Pri__Printer__pStr_name);
    __outAsync->invoke(__Pri__Printer__pStr_name, ::Ice::OperationMode::Normal, ::Ice::DefaultFormat, __ctx, 
        nullptr,
        nullptr,
        [&](::Ice::InputStream* __is)
        {
            Result_pStr v;
            __is->read(v.s);
            __is->read(v.returnValue);
            return v;
        });
}

const ::std::string&
Pri::PrinterPrx::ice_staticId()
{
    return Pri::Printer::ice_staticId();
}

bool
Pri::Printer::ice_isA(::std::string _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Pri__Printer_ids, __Pri__Printer_ids + 2, _s);
}

::std::vector< ::std::string>
Pri::Printer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Pri__Printer_ids[0], &__Pri__Printer_ids[2]);
}

const ::std::string&
Pri::Printer::ice_id(const ::Ice::Current&) const
{
    return __Pri__Printer_ids[1];
}

const ::std::string&
Pri::Printer::ice_staticId()
{
    return __Pri__Printer_ids[1];
}

::Ice::DispatchStatus
Pri::Printer::___pStr(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::OperationMode::Normal, __current.mode);
    __inS.readEmptyParams();
    ::std::string __p_s;
    ::std::string __ret = pStr(__p_s, __current);
    auto __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__p_s);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Pri::Printer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& c)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Pri__Printer_ops, __Pri__Printer_ops + 5, c.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, c.id, c.facet, c.operation);
    }

    switch(r.first - __Pri__Printer_ops)
    {
        case 0:
        {
            return ___ice_id(in, c);
        }
        case 1:
        {
            return ___ice_ids(in, c);
        }
        case 2:
        {
            return ___ice_isA(in, c);
        }
        case 3:
        {
            return ___ice_ping(in, c);
        }
        case 4:
        {
            return ___pStr(in, c);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, c.id, c.facet, c.operation);
}

#else // C++98 mapping

namespace
{

const ::std::string __Pri__Printer__pStr_name = "pStr";

}
::IceProxy::Ice::Object* ::IceProxy::Pri::upCast(::IceProxy::Pri::Printer* p) { return p; }

void
::IceProxy::Pri::__read(::Ice::InputStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Pri::Printer>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Pri::Printer;
        v->__copyFrom(proxy);
    }
}

::std::string
IceProxy::Pri::Printer::pStr(::std::string& __p_s, const ::Ice::Context& __ctx)
{
    __checkTwowayOnly(__Pri__Printer__pStr_name);
    ::IceInternal::Outgoing __og(this, __Pri__Printer__pStr_name, ::Ice::Normal, __ctx);
    __og.writeEmptyParams();
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_id());
            throw __uue;
        }
    }
    ::std::string __ret;
    ::Ice::InputStream* __is = __og.startReadParams();
    __is->read(__p_s);
    __is->read(__ret);
    __og.endReadParams();
    return __ret;
}

::Ice::AsyncResultPtr
IceProxy::Pri::Printer::__begin_pStr(const ::Ice::Context& __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Pri__Printer__pStr_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::CallbackOutgoing(this, __Pri__Printer__pStr_name, __del, __cookie);
    try
    {
        __result->prepare(__Pri__Printer__pStr_name, ::Ice::Normal, __ctx);
        __result->writeEmptyParams();
        __result->invoke(__Pri__Printer__pStr_name);
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

::std::string
IceProxy::Pri::Printer::end_pStr(::std::string& __p_s, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Pri__Printer__pStr_name);
    ::std::string __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_id());
        }
    }
    ::Ice::InputStream* __is = __result->__startReadParams();
    __is->read(__p_s);
    __is->read(__ret);
    __result->__endReadParams();
    return __ret;
}

const ::std::string&
IceProxy::Pri::Printer::ice_staticId()
{
    return ::Pri::Printer::ice_staticId();
}

::Ice::Object* Pri::upCast(::Pri::Printer* p) { return p; }

namespace
{
const ::std::string __Pri__Printer_ids[2] =
{
    "::Ice::Object",
    "::Pri::Printer"
};

}

bool
Pri::Printer::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Pri__Printer_ids, __Pri__Printer_ids + 2, _s);
}

::std::vector< ::std::string>
Pri::Printer::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Pri__Printer_ids[0], &__Pri__Printer_ids[2]);
}

const ::std::string&
Pri::Printer::ice_id(const ::Ice::Current&) const
{
    return __Pri__Printer_ids[1];
}

const ::std::string&
Pri::Printer::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Pri::Printer";
    return typeId;
#else
    return __Pri__Printer_ids[1];
#endif
}

::Ice::DispatchStatus
Pri::Printer::___pStr(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::std::string __p_s;
    ::std::string __ret = pStr(__p_s, __current);
    ::Ice::OutputStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__p_s);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Pri__Printer_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "pStr"
};

}

::Ice::DispatchStatus
Pri::Printer::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Pri__Printer_all, __Pri__Printer_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Pri__Printer_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___pStr(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Pri::Printer::__writeImpl(::Ice::OutputStream* __os) const
{
    __os->startSlice(ice_staticId(), -1, true);
    __os->endSlice();
}

void
Pri::Printer::__readImpl(::Ice::InputStream* __is)
{
    __is->startSlice();
    __is->endSlice();
}

void 
Pri::__patch(PrinterPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Pri::PrinterPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Pri::Printer::ice_staticId(), v);
    }
}

#endif
